### ISSUE TITLE
How do you use this?

### ISSUE THREAD

**Issue by jonathanng** [transcranial/jupyter-themer#2]
Love the idea.

It's not entirely clear how to use it.

I did something like this, but this had no effect.

    from jupythemer import jupythemer

    class Object(object):
        pass

    args = Object()
    args.layout     = 'wide'
    args.color      = None
    args.typography = None

    jupythemer.run(args)

**Comment by transcranial** [comment]
Since it modifies the css, you have to refresh your browser for the changes to apply. Also, check out the usage section of the readme - if you still have an old existing `~/.ipython` profile I think it may still try to automatically use that old profile.

Btw, I should write a convenience function wrapper for your code above. Would be nice to run it directly in the notebook as well. Thanks!
